### PR TITLE
added bcrypt_verify function for simplified comparisons

### PR DESCRIPTION
**Pull request by alexyoung91**
Makes usage of the library a little easier:

```
if (bcrypt_verify("thepassword", "hash")) {
    printf("The password matches\n");
} else {
    printf("The password does NOT match\n");
}
```

### CODE REVIEW

**Comment by rg3** [comment]
I'd prefer not to add that because by using strcmp we make the verification vulnerable to timing attacks. See "IMPORTANT NOTE" in bcrypt.h. So I think we should either leave that to the user as a problem or provide bcrypt_verify with a safe comparison function and update the documentation accordingly.

**Comment by alexyoung91** [comment]
I've implemented a timing safe string comparison similar to py-bcrypt and also renamed bcrypt_verify to bcrypt_checkpw. If there is any documentation changes you want me to make i can.

**Comment by aw** [comment]
:-1: 
I think this function is completely un-necessary in the bcrypt library. As @rg3 mentioned it can be implemented at the user level.

**Comment by rg3** [comment]
I finally merged your changes, but tuned the code with a few more commits.

I'm not a crypto expert at all, and I've been reading information about timing attacks and bcrypt. In theory, it seems using strcmp for the most common situations and use cases is fine because the timing information that would be leaked to an attacker would be of no use to guess the password faster. So we may be killing flies with cannons here. In any case, as doing a timing safe string comparison is easy, I see no reason not to use it.

Basically, I generalized timing_safe_strcmp and made it check the length earlier, which should be fine for our cases, and made it use unsigned chars for bitwise operations.

Then, I changed bcrypt_checkpw to make it possible to return an error code instead of a boolean result. This is important because now the success code is zero and non-zero results signal either errors or password mismatches. This can be considered a departure from py-bcrypt, but oh well...

And finally I updated the documentation, a few comments and the rest of the code.

Please feel free to point out problems and comment further.

**Comment by alexyoung91** [comment]
Thanks for reviewing timing_safe_strcmp. I am new to concepts like timing attacks and have not done a great deal of cryptography at all. I've just created a new pull request to remove a legacy variable. Error checking in bcrypt_checkpw is a good addition also!

**Pull request merged**
